name: com.example.simple_cubit_app
description: A simple Flutter application using the Cubit pattern for state management. The app includes a login screen with email and password fields, and a home screen with a logout button.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true